# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gulib_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(610, 308)
        self.totalTxt = QtWidgets.QLabel(Form)
        self.totalTxt.setGeometry(QtCore.QRect(190, 10, 221, 20))
        self.totalTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.totalTxt.setObjectName("totalTxt")
        self.listView = QtWidgets.QListView(Form)
        self.listView.setGeometry(QtCore.QRect(30, 50, 211, 241))
        self.listView.setObjectName("listView")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Laya - 类库导入"))
        self.totalTxt.setText(_translate("Form", "项目名称"))
