# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gulib_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(368, 311)
        self.totalTxt = QtWidgets.QLabel(Form)
        self.totalTxt.setGeometry(QtCore.QRect(120, 10, 141, 20))
        self.totalTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.totalTxt.setObjectName("totalTxt")
        self.listView = QtWidgets.QListView(Form)
        self.listView.setGeometry(QtCore.QRect(20, 40, 211, 241))
        self.listView.setObjectName("listView")
        self.checkBtn = QtWidgets.QCheckBox(Form)
        self.checkBtn.setGeometry(QtCore.QRect(20, 10, 101, 20))
        self.checkBtn.setObjectName("checkBtn")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 285, 211, 20))
        self.label.setStyleSheet("color:rgba(0, 0, 0, 100)")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.generateBtn = QtWidgets.QPushButton(Form)
        self.generateBtn.setGeometry(QtCore.QRect(240, 40, 121, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.generateBtn.setFont(font)
        self.generateBtn.setObjectName("generateBtn")
        self.tipsTxt = QtWidgets.QLabel(Form)
        self.tipsTxt.setGeometry(QtCore.QRect(250, 90, 60, 16))
        self.tipsTxt.setText("")
        self.tipsTxt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.tipsTxt.setObjectName("tipsTxt")
        self.errTxt = QtWidgets.QLabel(Form)
        self.errTxt.setGeometry(QtCore.QRect(250, 120, 91, 161))
        self.errTxt.setStyleSheet("color:rgb(209, 0, 28)")
        self.errTxt.setText("")
        self.errTxt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.errTxt.setObjectName("errTxt")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Laya - 类库导入"))
        self.totalTxt.setText(_translate("Form", "项目名称"))
        self.checkBtn.setText(_translate("Form", " 待定的文件"))
        self.label.setText(_translate("Form", "右键打开文件夹"))
        self.generateBtn.setText(_translate("Form", "开始导入"))
